{
 "title": "Matomo",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(config_device_type)"
   },
   { "name": "event_categroy", "label": "Event category", "query": "label_values(event_category)" },
   { "name": "rateInterval", "query": "4m" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Résolution d'écran",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_config_resolution[5m])) by (config_resolution)",
     "legendFormat": "{{config_resolution}}"
    }
   ]
  },
  {
   "title": "VIsitor retuned and new visitor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_visit{visitor_returning='returned'}[$rateInterval]))",
     "legendFormat": "Returned visitor"
    },
    {
     "expr": "sum(rate(matomo_visit {visitor_returning='new'}[$rateInterval]))",
     "legendFormat": "New visitor"
    }
   ]
  },
  {
   "title": "Device use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_general_info_user[$rateInterval])) by (config_device_type)",
     "legendFormat": "{{config_device_type}}"
    }
   ]
  },
  {
   "title": "Browser use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_general_info_user[$rateInterval])) by (browser_name_version)",
     "legendFormat": "{{browser_name_version}}"
    }
   ]
  },
  {
   "title": "OS use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_general_info_user[$rateInterval])) by (config_os)",
     "legendFormat": "{{config_os}}"
    }
   ]
  },
  {
   "title": "Event through time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_event_name[$rateInterval])) by (event_name)",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Event category through time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_event_name[$rateInterval])) by (event_category)",
     "legendFormat": "{{event_category}}"
    }
   ]
  },
  {
   "title": "Event by visit through time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_event_name[$rateInterval])) by (event_name, id_visit)",
     "legendFormat": "{{id_visit}} - {{event_name}}"
    }
   ]
  },
  {
   "title": "Total's actions by Visit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_event_name[$rateInterval])) by (id_visit)",
     "legendFormat": "{{id_visit}} "
    }
   ]
  },
  {
   "title": "Event by Browser through time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_event_name[$rateInterval])) by (event_name, browser_name)",
     "legendFormat": "{{browser_name}} - {{event_name}} "
    }
   ]
  },
  {
   "title": "Total's actions by Browser",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_event_name[$rateInterval])) by (browser_name)",
     "legendFormat": "{{browser_name}}"
    }
   ]
  },
  {
   "title": "Event by visitor through time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_event_name[$rateInterval])) by (event_name, id_visitor)",
     "legendFormat": "{{id_visitor}} - {{event_name}}"
    }
   ]
  },
  {
   "title": "Total's actions by Visitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matomo_event_name[$rateInterval])) by (id_visitor)",
     "legendFormat": "{{id_visitor}}"
    }
   ]
  },
  {
   "title": "Variable",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event through type by $device",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(matomo_event_name{config_device_type='$device'}[$rateInterval])) by (event_name)",
       "legendFormat": "{{event_name}}"
      }
     ]
    },
    {
     "title": "Event through time by $event_categroy",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(matomo_event_name{event_category='$event_categroy'}[$rateInterval])) by (event_name)",
       "legendFormat": "{{event_name}}"
      }
     ]
    }
   ]
  }
 ]
}